site_name: GivePulse Documentation
site_url: 'https://jamesbrainard.github.io/givepulse/'
nav:
  - Home: index.md
  - Students: students.md
  - Event Managers: event_managers.md
  - Staff: staff.md
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle: 
        icon: material/toggle-switch-off-outline
        name: Dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle: 
        icon: material/toggle-switch
        name: Light mode
      primary: teal
      accent: lime
extra_css:
  - extra.css
plugins:
  - redirects:
      redirect_maps:
        index.md: /givepulse/welcome